use_frameworks!

target 'NNTabularViewController_Example' do
  pod 'NNTabularViewController', :path => '../'

  target 'NNTabularViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
