use_frameworks!

#sources
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/ChandlerNguyen/pods-spec-ios.git'

target 'NNTabularViewController_Example' do
  pod 'NNTabularViewController', :path => '../'

  target 'NNTabularViewController_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
